apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoddo-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ddoddo-backend
  template:
    metadata:
      labels:
        app: ddoddo-backend
    spec:
      containers:
        - name: ddoddo-backend
          image: namung08/ddoddo-backend:v1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ddoddo-config-backend
            - secretRef:
                name: ddoddo-secret-backend
