apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoddo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddoddo-db
  template:
    metadata:
      labels:
        app: ddoddo-db
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ddoddo-config-database
            - secretRef:
                name: ddoddo-secret-database
