apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: namung08/k8s-labs-todo-backend:v1.5
          ports:
            - containerPort: 8080
          env:
            - name: PGURL
              value: jdbc:postgresql://todo-db-service:5432/userdb
            - name: PGUSER
              value: user
            - name: PGPASS
              value: user1234
            - name: JWT_SECRET
            - name: JWT_expirationMs
              value: "36000"
