apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddoddo-market-chart.fullname" . }}-service
  labels:
    {{- include "ddoddo-market-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "ddoddo-market-chart.selectorLabels" . | nindent 4 }}


