apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf:
    # 이 파일이 Nginx Pod의 기본 설정 파일 역할을 하게 됩니다.
    server {
    listen       80;
    server_name  localhost;
    default_type text/plain;
    
    # 모든 요청(/)에 대해 200 OK 상태 코드와 함께
    # "Hello, ConfigMap Volume!" 메시지를 반환합니다.
    location / {
    return 200 "Hello, ConfigMap Volume!\n";
    }
    }
