apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list-chart.fullname" . }}-backend
  labels:
    {{- include "todo-list-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
    {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort.enabled }}
      nodePort: {{ .Values.backend.service.nodePort.port }}
    {{- end }}
  selector:
    {{- include "todo-list-chart.backend.selectorLabels" . | nindent 4 }}
