
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: namung08/k8s-labs-todo-backend:latest # Docker Hub 사용자 이름으로 변경 필요
      ports:
        - containerPort: 5000
      env:
        - name: PGUSER
          value: "user"
        - name: PGHOST
          value: "postgres-pod" # 참고: 현재는 Pod 내부의 localhost를 가리키므로 DB에 연결할 수 없음
        - name: PGDATABASE
          value: "tododb"
        - name: PGPASSWORD
          value: "password"
        - name: PGPORT
          value: "5432"
